import Head from "next/head";
import { useEffect, useState } from "react";
import { User } from "@prisma/client";
import axios, { AxiosError } from "axios";

export default function Home() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    axios
      .get<{users: User[]}>("/api/hello")
      .then((response) => {
        setUsers(response.data.users);
        console.log(JSON.stringify(response.data));
      })
      .catch((err: AxiosError) => {
        console.log(err.toJSON());
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {users.map((user, i) => (
            <li key={i}>
              <p>{user.id}</p>
              <p>{user.name}</p>
              <p>{user.email}</p>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
