import Head from "next/head";
import { useEffect, useState } from "react";
import { User } from "@prisma/client";
import axios, { AxiosError } from "axios";
import Link from "next/link";

import styles from "@/styles/Index.module.css"

export default function Home() {
  const [users, setUsers] = useState<User[]>([]);
  const [userEmail, setUserEmail] = useState<string>("");
  const [name, setName] = useState<string>("");

  const updateUsers = () => {
    axios
      .get<{ users: User[] }>("/api/hello")
      .then((response) => {
        setUsers(response.data.users);
        console.log(JSON.stringify(response.data));
      })
      .catch((err: AxiosError) => {
        console.log(err.toJSON());
      });
  };

  useEffect(updateUsers, []);

  return (
    <div className={styles.index}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {users.map((user, i) => (
            <li key={i}>
              <br />
              <p>
                {i} {user.name} {user.email}
              </p>
            </li>
          ))}
        </ul>

        <Link href="/me">
          Me page
        </Link>

        <Link href="/signup">
          Account Creation
        </Link>
      </main>
    </div>
  );
}
