import Head from "next/head";
import { useEffect, useState } from "react";
import { User } from "@prisma/client";
import axios, { AxiosError } from "axios";

export default function Home() {
  const [users, setUsers] = useState<User[]>([]);
  const [userEmail, setUserEmail] = useState<string>("");
  const [name, setName] = useState<string>("");

  const submitInfo = async () => {
    axios
      .post("/api/users", {
        email: userEmail,
        name: name,
      })
      .then(() => {
        setUserEmail("");
        setName("");
        updateUsers();
      });
  };

  const updateUsers = () => {
    axios
      .get<{ users: User[] }>("/api/hello")
      .then((response) => {
        setUsers(response.data.users);
        console.log(JSON.stringify(response.data));
      })
      .catch((err: AxiosError) => {
        console.log(err.toJSON());
      });
  };

  useEffect(updateUsers, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <br />
        <label>Enter e-mail</label>
        <input
          type="email"
          onChange={(text) => setUserEmail(text.target.value)}
          value={userEmail}
        />
        <label>Enter Name</label>
        <input
          type="text"
          onChange={(text) => setName(text.target.value)}
          value={name}
        />
        <button onClick={submitInfo}>Submit</button>

        <ul>
          {users.map((user, i) => (
            <li key={i}>
              <br />
              <p>{user.id} {user.name} {user.email}</p>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
