# todo, set up prisma building and migration
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  labels:
    app: nextjs-app-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
  labels:
    app: nextjs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: {{ .Values.nextjsAppImage }}
          env:
            - name: MYSQL_URL
              value: mysql-service
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: USERNAME
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: USER_PASSWORD
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEXTAUTH_URL
            - name: DATABASE_URL
              value: mysql://$(MYSQL_USERNAME):$(MYSQL_PASSWORD)@mysql-service:3306/$(MYSQL_DATABASE)
          ports:
            - containerPort: 3000
      initContainers:
        - name: wait-on-db
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql-service; do echo waiting for myservice; sleep 2; done",
            ]
